let vgk_c = [
    [ 'Abū Dabī'],  //0
    [ 'Kabula'],  //1
    [ 'Tirāna'],  //2
    [ 'Alžīra'],  //3
    [ 'Andora la Velja'],  //4
    [ 'Veli'],  //5
    [ 'Luanda'],  //6
    [ '–'],  //7
    [ 'Sentdžonsa'],  //8
    [ 'Buenosairesa'],  //9
    [ 'Erevāna'],  //10
    [ 'Oranjestade'],  //11
    [ 'Vašingtona'],  //12
    [ '–'],  //13
    [ 'Šarlote Amālija'],  //14
    [ 'Kanbera'],  //15
    [ 'Vīne'],  //16
    [ 'Dili'],  //17
    [ 'Pagopago'],  //18
    [ 'Baku'],  //19
    [ 'Naso'],  //20
    [ 'Manāma'],  //21
    [ 'Minska'],  //22
    [ 'Daka'],  //23
    [ 'Bridžtauna'],  //24
    [ 'Belmopana'],  //25
    [ 'Brisele'],  //26
    [ 'Portonovo'],  //27
    [ 'Hamiltona'],  //28
    [ 'Sukre'],  //29
    [ 'Sarajeva'],  //30
    [ 'Gaborone'],  //31
    [ 'Brazilja'],  //32
    [ 'Rodtauna'],  //33
    [ 'Bandarseribegavana'],  //34
    [ 'Sofija'],  //35
    [ 'Vagadugu'],  //36
    [ 'Bužumbura'],  //37
    [ 'Timpu'],  //38
    [ '–'],  //39
    [ 'Bangi'],  //40
    [ 'Ndžamena'],  //41
    [ 'Prāga'],  //42
    [ 'Santjago'],  //43
    [ 'Kopenhāgena'],  //44
    [ 'Pretorija / Keiptauna'],  //45
    [ 'Kingedvardpointa (admin. centrs)'],  //46
    [ 'Seula'],  //47
    [ 'Džūba'],  //48
    [ 'Rozo'],  //49
    [ 'Santodomingo'],  //50
    [ 'Sentheljēra'],  //51
    [ 'Džibuti'],  //52
    [ 'Kaira'],  //53
    [ 'Kito'],  //54
    [ 'Malabo'],  //55
    [ 'Asmera'],  //56
    [ 'Adisabeba'],  //57
    [ 'Stenlija'],  //58
    [ 'Touršhavna'],  //59
    [ 'Suva'],  //60
    [ 'Manila'],  //61
    [ 'Parīze'],  //62
    [ '–'],  //63
    [ 'Kajenna (admin. centrs)'],  //64
    [ 'Papeete'],  //65
    [ 'Librevila'],  //66
    [ 'Džordžtauna'],  //67
    [ 'Bandžula'],  //68
    [ 'Akra'],  //69
    [ 'Sentpīterporta'],  //70
    [ 'Gibraltāra'],  //71
    [ 'Sentdžordžesa'],  //72
    [ 'Nūka'],  //73
    [ 'Atēnas'],  //74
    [ 'Tbilisi'],  //75
    [ 'Hagātņa'],  //76
    [ 'Bastēra (admin. centrs)'],  //77
    [ 'Gvatemala'],  //78
    [ 'Konakri'],  //79
    [ 'Bisava'],  //80
    [ 'Portoprensa'],  //81
    [ '–'],  //82
    [ 'Tegusigalpa'],  //83
    [ 'Viktorija (admin. centrs)'],  //84
    [ 'Zagreba'],  //85
    [ 'Tallina'],  //86
    [ 'Jaundeli'],  //87
    [ 'Kempdžastisa (admin. centrs)'],  //88
    [ 'Džakarta'],  //89
    [ 'Bagdāde'],  //90
    [ 'Teherāna'],  //91
    [ 'Dublina'],  //92
    [ 'Reikjavīka'],  //93
    [ 'Roma'],  //94
    [ 'Jeruzaleme'],  //95
    [ 'Kingstona'],  //96
    [ 'Tokija'],  //97
    [ 'Numea'],  //98
    [ 'Velingtona'],  //99
    [ 'Sana'],  //100
    [ 'Ammāna'],  //101
    [ 'Praja'],  //102
    [ 'Džordžtauna'],  //103
    [ 'Pnompeņa'],  //104
    [ 'Jaunde'],  //105
    [ 'Otava'],  //106
    [ 'Kralendeika, Oranjestade (Sintēstatiusa), Bote'],  //107
    [ 'Doha'],  //108
    [ 'Astana'],  //109
    [ 'Nairobi'],  //110
    [ 'Nikosija'],  //111
    [ 'Vilemstade'],  //112
    [ 'Biškeka'],  //113
    [ 'Teinainano'],  //114
    [ 'Vestailenda'],  //115
    [ 'Bogota'],  //116
    [ 'Moroni'],  //117
    [ 'Kinšasa'],  //118
    [ 'Brazavila'],  //119
    [ 'Priština'],  //120
    [ 'Sanhosē'],  //121
    [ 'Jamusukro'],  //122
    [ 'Maskava'],  //123
    [ 'Havana'],  //124
    [ 'Avarua'],  //125
    [ 'Kuveita'],  //126
    [ 'Pekina'],  //127
    [ 'Vjenčana'],  //128
    [ 'Rīga'],  //129
    [ 'Maseru'],  //130
    [ 'Beirūta'],  //131
    [ 'Monrovija'],  //132
    [ 'Tripole'],  //133
    [ 'Londona'],  //134
    [ 'Viļņa'],  //135
    [ 'Vaduca'],  //136
    [ 'Luksemburga'],  //137
    [ 'Antananarivu'],  //138
    [ 'Dzaudzi'],  //139
    [ 'Aomiņa'],  //140
    [ 'Kualalumpura'],  //141
    [ 'Lilongve'],  //142
    [ 'Male'],  //143
    [ 'Bamako'],  //144
    [ 'Valleta'],  //145
    [ 'Rabāta'],  //146
    [ 'Madžuro'],  //147
    [ 'Fordefransa (admin. centrs)'],  //148
    [ 'Portluī'],  //149
    [ 'Nuakšota'],  //150
    [ 'Mehiko'],  //151
    [ 'Podgorica'],  //152
    [ 'Daglasa (admin. centrs)'],  //153
    [ 'Palikira'],  //154
    [ 'Nepjido'],  //155
    [ 'Kišiņeva'],  //156
    [ 'Monako'],  //157
    [ 'Ulanbatora'],  //158
    [ 'Plimuta'],  //159
    [ 'Maputu'],  //160
    [ 'Vindhuka'],  //161
    [ 'oficiālas galvaspilsētas nav;'],  //162
    [ 'Katmandu'],  //163
    [ 'Amsterdama / Hāga'],  //164
    [ 'Niameja'],  //165
    [ 'Abudža'],  //166
    [ 'Managva'],  //167
    [ 'Alofi'],  //168
    [ 'Kingstona'],  //169
    [ 'Oslo'],  //170
    [ 'Mariehamna'],  //171
    [ 'Maskata'],  //172
    [ 'Islāmābāda'],  //173
    [ 'Melegeoka'],  //174
    [ 'Jeruzaleme – proklamēta;'],  //175
    [ 'Panama'],  //176
    [ 'Portmorsbija'],  //177
    [ 'Asunsjona'],  //178
    [ 'Lima'],  //179
    [ 'Adamstauna'],  //180
    [ 'Varšava'],  //181
    [ 'Lisabona'],  //182
    [ 'Sanhuana'],  //183
    [ 'Sendenī (admin. centrs)'],  //184
    [ 'Ajūna'],  //185
    [ 'Kigali'],  //186
    [ 'Bukareste'],  //187
    [ 'Sansalvadora'],  //188
    [ 'Apija'],  //189
    [ 'Sanmarīno'],  //190
    [ 'Santomē'],  //191
    [ 'Rijāda'],  //192
    [ 'Viktorija'],  //193
    [ 'Gustavija'],  //194
    [ 'Dakāra'],  //195
    [ 'Marigo'],  //196
    [ 'Senpjēra'],  //197
    [ 'Bastera'],  //198
    [ 'Kastri'],  //199
    [ 'Kingstauna'],  //200
    [ 'Belgrada'],  //201
    [ 'Singapūra'],  //202
    [ 'Filipsburga'],  //203
    [ 'Damaska'],  //204
    [ 'Frītauna'],  //205
    [ 'Bratislava'],  //206
    [ 'Ļubļana'],  //207
    [ 'Mogadīšo'],  //208
    [ 'Helsinki'],  //209
    [ 'Madride'],  //210
    [ 'Hartūma'],  //211
    [ 'Paramaribo'],  //212
    [ 'Longjērbīene (admin. centrs)'],  //213
    [ 'Mbabane'],  //214
    [ 'Džeimstauna'],  //215
    [ 'Šrī Džajavardenepura Kote'],  //216
    [ 'Berne'],  //217
    [ 'Dušanbe'],  //218
    [ 'Taibeja'],  //219
    [ 'Bangkoka'],  //220
    [ 'Dodoma'],  //221
    [ 'Kokbērntauna'],  //222
    [ 'Lome'],  //223
    [ 'Fakaofo'],  //224
    [ 'Nukualofa'],  //225
    [ 'Portofspeina'],  //226
    [ 'Tunisa'],  //227
    [ 'Ankara'],  //228
    [ 'Ašgabata'],  //229
    [ 'Funafuti'],  //230
    [ 'Kampala'],  //231
    [ 'Kijeva'],  //232
    [ 'Budapešta'],  //233
    [ 'Montevideo'],  //234
    [ 'Taškenta'],  //235
    [ 'Berlīne'],  //236
    [ 'Vila'],  //237
    [ 'Vatikāns'],  //238
    [ 'Karakasa'],  //239
    [ 'Hanoja'],  //240
    [ 'Matāutu'],  //241
    [ 'Honiara'],  //242
    [ 'Lusaka'],  //243
    [ 'Phenjana'],  //244
    [ 'Skopje'],  //245
    [ 'Garapana'],  //246
    [ 'Flaingfiškouva'],  //247
    [ 'Harare'],  //248
    [ 'Stokholma'],  //249  
    ];