let vgk = [
    [ 'AE', 'Apvienotie Arābu Emirāti', 'Abū Dabī', 'https://flagpedia.net/data/flags/w580/ae.png'], 
[ 'AF', 'Afganistānas Islāma Republika', 'Kabula', 'https://flagpedia.net/data/flags/w580/af.png'], 
[ 'AL', 'Albānijas Republika', 'Tirāna', 'https://flagpedia.net/data/flags/w580/al.png'], 
[ 'DZ', 'Alžīrijas Tautas Demokrātiskā Republika', 'Alžīra', 'https://flagpedia.net/data/flags/w580/dz.png'], 
[ 'AD', 'Andoras Firstiste', 'Andora la Velja', 'https://flagpedia.net/data/flags/w580/ad.png'], 
[ 'AI', 'Angiljas teritorija', 'Veli', 'https://flagpedia.net/data/flags/w580/ai.png'], 
[ 'AO', 'Angolas Republika', 'Luanda', 'https://flagpedia.net/data/flags/w580/ao.png'], 
[ 'AQ', '(kontinents: Antarktīda)', '–', 'https://flagpedia.net/data/flags/w580/aq.png'], 
[ 'AG', 'Antigva un Barbuda', 'Sentdžonsa', 'https://flagpedia.net/data/flags/w580/ag.png'], 
[ 'AR', 'Argentīnas Republika', 'Buenosairesa', 'https://flagpedia.net/data/flags/w580/ar.png'], 
[ 'AM', 'Armēnijas Republika', 'Erevāna', 'https://flagpedia.net/data/flags/w580/am.png'], 
[ 'AW', 'Aruba', 'Oranjestade', 'https://flagpedia.net/data/flags/w580/aw.png'], 
[ 'US', 'Amerikas Savienotās Valstis', 'Vašingtona', 'https://flagpedia.net/data/flags/w580/us.png'], 
[ 'UM', 'ASV Mazās aizjūras teritorijas', '–', 'https://flagpedia.net/data/flags/w580/um.png'], 
[ 'VI', 'ASV Virdžīnu salu teritorija', 'Šarlote Amālija', 'https://flagpedia.net/data/flags/w580/vi.png'], 
[ 'AU', 'Austrālijas Savienība', 'Kanbera', 'https://flagpedia.net/data/flags/w580/au.png'], 
[ 'AT', 'Austrijas Republika', 'Vīne', 'https://flagpedia.net/data/flags/w580/at.png'], 
[ 'TL', 'Austrumtimoras Demokrātiskā Republika', 'Dili', 'https://flagpedia.net/data/flags/w580/tl.png'], 
[ 'AS', 'ASV Samoa teritorija', 'Pagopago', 'https://flagpedia.net/data/flags/w580/as.png'], 
[ 'AZ', 'Azerbaidžānas Republika', 'Baku', 'https://flagpedia.net/data/flags/w580/az.png'], 
[ 'BS', 'Bahamu Sadraudzība', 'Naso', 'https://flagpedia.net/data/flags/w580/bs.png'], 
[ 'BH', 'Bahreinas Karaliste', 'Manāma', 'https://flagpedia.net/data/flags/w580/bh.png'], 
[ 'BY', 'Baltkrievijas Republika', 'Minska', 'https://flagpedia.net/data/flags/w580/by.png'], 
[ 'BD', 'Bangladešas Tautas Republika', 'Daka', 'https://flagpedia.net/data/flags/w580/bd.png'], 
[ 'BB', 'Barbadosa', 'Bridžtauna', 'https://flagpedia.net/data/flags/w580/bb.png'], 
[ 'BZ', 'Beliza', 'Belmopana', 'https://flagpedia.net/data/flags/w580/bz.png'], 
[ 'BE', 'Beļģijas Karaliste', 'Brisele', 'https://flagpedia.net/data/flags/w580/be.png'], 
[ 'BJ', 'Beninas Republika', 'Portonovo', 'https://flagpedia.net/data/flags/w580/bj.png'], 
[ 'BM', 'Bermudu salu teritorija', 'Hamiltona', 'https://flagpedia.net/data/flags/w580/bm.png'], 
[ 'BO', 'Bolīvijas Daudznacionālā Valsts', 'Sukre', 'https://flagpedia.net/data/flags/w580/bo.png'], 
[ 'BA', 'Bosnija un Hercegovina', 'Sarajeva', 'https://flagpedia.net/data/flags/w580/ba.png'], 
[ 'BW', 'Botsvānas Republika', 'Gaborone', 'https://flagpedia.net/data/flags/w580/bw.png'], 
[ 'BR', 'Brazīlijas Federatīvā Republika', 'Brazilja', 'https://flagpedia.net/data/flags/w580/br.png'], 
[ 'VG', 'Britu Virdžīnu salu teritorija', 'Rodtauna', 'https://flagpedia.net/data/flags/w580/vg.png'], 
[ 'BN', 'Bruneja Darusalama', 'Bandarseribegavana', 'https://flagpedia.net/data/flags/w580/bn.png'], 
[ 'BG', 'Bulgārijas Republika', 'Sofija', 'https://flagpedia.net/data/flags/w580/bg.png'], 
[ 'BF', 'Burkinafaso', 'Vagadugu', 'https://flagpedia.net/data/flags/w580/bf.png'], 
[ 'BI', 'Burundijas Republika', 'Bužumbura', 'https://flagpedia.net/data/flags/w580/bi.png'], 
[ 'BT', 'Butānas Karaliste', 'Timpu', 'https://flagpedia.net/data/flags/w580/bt.png'], 
[ 'BV', 'Buvē sala', '–', 'https://flagpedia.net/data/flags/w580/bv.png'], 
[ 'CF', 'Centrālāfrikas Republika', 'Bangi', 'https://flagpedia.net/data/flags/w580/cf.png'], 
[ 'TD', 'Čadas Republika', 'Ndžamena', 'https://flagpedia.net/data/flags/w580/td.png'], 
[ 'CZ', 'Čehijas Republika', 'Prāga', 'https://flagpedia.net/data/flags/w580/cz.png'], 
[ 'CL', 'Čīles Republika', 'Santjago', 'https://flagpedia.net/data/flags/w580/cl.png'], 
[ 'DK', 'Dānijas Karaliste', 'Kopenhāgena', 'https://flagpedia.net/data/flags/w580/dk.png'], 
[ 'ZA', 'Dienvidāfrikas Republika', 'Pretorija / Keiptauna', 'https://flagpedia.net/data/flags/w580/za.png'], 
[ 'GS', 'Dienviddžordžija un Dienvidsendviču salas', 'Kingedvardpointa (admin. centrs)', 'https://flagpedia.net/data/flags/w580/gs.png'], 
[ 'KR', 'Korejas Republika', 'Seula', 'https://flagpedia.net/data/flags/w580/kr.png'], 
[ 'SS', 'Dienvidsudānas Republika', 'Džūba', 'https://flagpedia.net/data/flags/w580/ss.png'], 
[ 'DM', 'Dominikas Sadraudzība', 'Rozo', 'https://flagpedia.net/data/flags/w580/dm.png'], 
[ 'DO', 'Dominikānas Republika', 'Santodomingo', 'https://flagpedia.net/data/flags/w580/do.png'], 
[ 'JE', 'Džērsija', 'Sentheljēra', 'https://flagpedia.net/data/flags/w580/je.png'], 
[ 'DJ', 'Džibutijas Republika', 'Džibuti', 'https://flagpedia.net/data/flags/w580/dj.png'], 
[ 'EG', 'Ēģiptes Arābu Republika', 'Kaira', 'https://flagpedia.net/data/flags/w580/eg.png'], 
[ 'EC', 'Ekvadoras Republika', 'Kito', 'https://flagpedia.net/data/flags/w580/ec.png'], 
[ 'GQ', 'Ekvatoriālās Gvinejas Republika', 'Malabo', 'https://flagpedia.net/data/flags/w580/gq.png'], 
[ 'ER', 'Eritrejas Valsts', 'Asmera', 'https://flagpedia.net/data/flags/w580/er.png'], 
[ 'ET', 'Etiopijas Federatīvā Demokrātiskā Republika', 'Adisabeba', 'https://flagpedia.net/data/flags/w580/et.png'], 
[ 'FK', 'Folklenda (Malvinu) salu teritorija', 'Stenlija', 'https://flagpedia.net/data/flags/w580/fk.png'], 
[ 'FO', 'Fēru salas', 'Touršhavna', 'https://flagpedia.net/data/flags/w580/fo.png'], 
[ 'FJ', 'Fidži Republika', 'Suva', 'https://flagpedia.net/data/flags/w580/fj.png'], 
[ 'PH', 'Filipīnu Republika', 'Manila', 'https://flagpedia.net/data/flags/w580/ph.png'], 
[ 'FR', 'Francijas Republika', 'Parīze', 'https://flagpedia.net/data/flags/w580/fr.png'], 
[ 'TF', 'Francijas Dienvidjūru un Antarktikas teritorija', '–', 'https://flagpedia.net/data/flags/w580/tf.png'], 
[ 'GF', 'Francijas Gviānas departaments', 'Kajenna (admin. centrs)', 'https://flagpedia.net/data/flags/w580/gf.png'], 
[ 'PF', 'Francijas Polinēzijas teritorija', 'Papeete', 'https://flagpedia.net/data/flags/w580/pf.png'], 
[ 'GA', 'Gabonas Republika', 'Librevila', 'https://flagpedia.net/data/flags/w580/ga.png'], 
[ 'GY', 'Gajānas Kooperatīvā Republika', 'Džordžtauna', 'https://flagpedia.net/data/flags/w580/gy.png'], 
[ 'GM', 'Gambijas Republika', 'Bandžula', 'https://flagpedia.net/data/flags/w580/gm.png'], 
[ 'GH', 'Ganas Republika', 'Akra', 'https://flagpedia.net/data/flags/w580/gh.png'], 
[ 'GG', 'Gērnsija', 'Sentpīterporta', 'https://flagpedia.net/data/flags/w580/gg.png'], 
[ 'GI', 'Gibraltāra teritorija', 'Gibraltāra', 'https://flagpedia.net/data/flags/w580/gi.png'], 
[ 'GD', 'Grenāda', 'Sentdžordžesa', 'https://flagpedia.net/data/flags/w580/gd.png'], 
[ 'GL', 'Grenlande', 'Nūka', 'https://flagpedia.net/data/flags/w580/gl.png'], 
[ 'GR', 'Grieķijas Republika', 'Atēnas', 'https://flagpedia.net/data/flags/w580/gr.png'], 
[ 'GE', 'Gruzija', 'Tbilisi', 'https://flagpedia.net/data/flags/w580/ge.png'], 
[ 'GU', 'ASV Guamas teritorija', 'Hagātņa', 'https://flagpedia.net/data/flags/w580/gu.png'], 
[ 'GP', 'Francijas Gvadelupas departaments', 'Bastēra (admin. centrs)', 'https://flagpedia.net/data/flags/w580/gp.png'], 
[ 'GT', 'Gvatemalas Republika', 'Gvatemala', 'https://flagpedia.net/data/flags/w580/gt.png'], 
[ 'GN', 'Gvinejas Republika', 'Konakri', 'https://flagpedia.net/data/flags/w580/gn.png'], 
[ 'GW', 'Gvinejas–Bisavas Republika', 'Bisava', 'https://flagpedia.net/data/flags/w580/gw.png'], 
[ 'HT', 'Haiti Republika', 'Portoprensa', 'https://flagpedia.net/data/flags/w580/ht.png'], 
[ 'HM', 'Hērda salas un Makdonalda salu teritorija', '–', 'https://flagpedia.net/data/flags/w580/hm.png'], 
[ 'HN', 'Hondurasas Republika', 'Tegusigalpa', 'https://flagpedia.net/data/flags/w580/hn.png'], 
[ 'HK', 'Honkongas / Sjanganas īpašais administratīvais rajons (ĶTR)', 'Viktorija (admin. centrs)', 'https://flagpedia.net/data/flags/w580/hk.png'], 
[ 'HR', 'Horvātijas Republika', 'Zagreba', 'https://flagpedia.net/data/flags/w580/hr.png'], 
[ 'EE', 'Igaunijas Republika', 'Tallina', 'https://flagpedia.net/data/flags/w580/ee.png'], 
[ 'IN', 'Indijas Republika', 'Jaundeli', 'https://flagpedia.net/data/flags/w580/in.png'], 
[ 'IO', 'Indijas Okeāna Britu teritorija', 'Kempdžastisa (admin. centrs)', 'https://flagpedia.net/data/flags/w580/io.png'], 
[ 'ID', 'Indonēzijas Republika', 'Džakarta', 'https://flagpedia.net/data/flags/w580/id.png'], 
[ 'IQ', 'Irākas Republika', 'Bagdāde', 'https://flagpedia.net/data/flags/w580/iq.png'], 
[ 'IR', 'Irānas Islāma Republika', 'Teherāna', 'https://flagpedia.net/data/flags/w580/ir.png'], 
[ 'IE', 'Īrijas Republika', 'Dublina', 'https://flagpedia.net/data/flags/w580/ie.png'], 
[ 'IS', 'Islandes Republika', 'Reikjavīka', 'https://flagpedia.net/data/flags/w580/is.png'], 
[ 'IT', 'Itālijas Republika', 'Roma', 'https://flagpedia.net/data/flags/w580/it.png'], 
[ 'IL', 'Izraēlas Valsts', 'Jeruzaleme', 'https://flagpedia.net/data/flags/w580/il.png'], 
[ 'JM', 'Jamaika', 'Kingstona', 'https://flagpedia.net/data/flags/w580/jm.png'], 
[ 'JP', 'Japāna', 'Tokija', 'https://flagpedia.net/data/flags/w580/jp.png'], 
[ 'NC', 'Francijas Jaunkaledonijas teritorija', 'Numea', 'https://flagpedia.net/data/flags/w580/nc.png'], 
[ 'NZ', 'Jaunzēlande', 'Velingtona', 'https://flagpedia.net/data/flags/w580/nz.png'], 
[ 'YE', 'Jemenas Republika', 'Sana', 'https://flagpedia.net/data/flags/w580/ye.png'], 
[ 'JO', 'Jordānijas Hāšimītu Karaliste', 'Ammāna', 'https://flagpedia.net/data/flags/w580/jo.png'], 
[ 'CV', 'Kaboverdes Republika', 'Praja', 'https://flagpedia.net/data/flags/w580/cv.png'], 
[ 'KY', 'Kaimanu salu teritorija', 'Džordžtauna', 'https://flagpedia.net/data/flags/w580/ky.png'], 
[ 'KH', 'Kambodžas Karaliste', 'Pnompeņa', 'https://flagpedia.net/data/flags/w580/kh.png'], 
[ 'CM', 'Kamerūnas Republika', 'Jaunde', 'https://flagpedia.net/data/flags/w580/cm.png'], 
[ 'CA', 'Kanāda', 'Otava', 'https://flagpedia.net/data/flags/w580/ca.png'], 
[ 'BQ', 'Bonaire, Sintēstatiusa un Saba', 'Kralendeika, Oranjestade (Sintēstatiusa), Bote', 'https://flagpedia.net/data/flags/w580/bq.png'], 
[ 'QA', 'Kataras Valsts', 'Doha', 'https://flagpedia.net/data/flags/w580/qa.png'], 
[ 'KZ', 'Kazahstānas Republika', 'Astana', 'https://flagpedia.net/data/flags/w580/kz.png'], 
[ 'KE', 'Kenijas Republika', 'Nairobi', 'https://flagpedia.net/data/flags/w580/ke.png'], 
[ 'CY', 'Kipras Republika', 'Nikosija', 'https://flagpedia.net/data/flags/w580/cy.png'], 
[ 'CW', 'Kirasao Valsts', 'Vilemstade', 'https://flagpedia.net/data/flags/w580/cw.png'], 
[ 'KG', 'Kirgīzu Republika', 'Biškeka', 'https://flagpedia.net/data/flags/w580/kg.png'], 
[ 'KI', 'Kiribati Republika', 'Teinainano', 'https://flagpedia.net/data/flags/w580/ki.png'], 
[ 'CC', 'Kokosu un Kīlinga salu teritorija', 'Vestailenda', 'https://flagpedia.net/data/flags/w580/cc.png'], 
[ 'CO', 'Kolumbijas Republika', 'Bogota', 'https://flagpedia.net/data/flags/w580/co.png'], 
[ 'KM', 'Komoru Savienība', 'Moroni', 'https://flagpedia.net/data/flags/w580/km.png'], 
[ 'CD', 'Kongo Demokrātiskā Republika', 'Kinšasa', 'https://flagpedia.net/data/flags/w580/cd.png'], 
[ 'CG', 'Kongo Republika', 'Brazavila', 'https://flagpedia.net/data/flags/w580/cg.png'], 
[ 'XK', 'Kosovas Republika', 'Priština', 'https://flagpedia.net/data/flags/w580/xk.png'], 
[ 'CR', 'Kostarikas Republika', 'Sanhosē', 'https://flagpedia.net/data/flags/w580/cr.png'], 
[ 'CI', 'Kotdivuāras Republika', 'Jamusukro', 'https://flagpedia.net/data/flags/w580/ci.png'], 
[ 'RU', 'Krievijas Federācija', 'Maskava', 'https://flagpedia.net/data/flags/w580/ru.png'], 
[ 'CU', 'Kubas Republika', 'Havana', 'https://flagpedia.net/data/flags/w580/cu.png'], 
[ 'CK', 'Kuka Salas', 'Avarua', 'https://flagpedia.net/data/flags/w580/ck.png'], 
[ 'KW', 'Kuveitas Valsts', 'Kuveita', 'https://flagpedia.net/data/flags/w580/kw.png'], 
[ 'CN', 'Ķīnas Tautas Republika (ĶTR)', 'Pekina', 'https://flagpedia.net/data/flags/w580/cn.png'], 
[ 'LA', 'Laosas Tautas Demokrātiskā Republika', 'Vjenčana', 'https://flagpedia.net/data/flags/w580/la.png'], 
[ 'LV', 'Latvijas Republika', 'Rīga', 'https://flagpedia.net/data/flags/w580/lv.png'], 
[ 'LS', 'Lesoto Karaliste', 'Maseru', 'https://flagpedia.net/data/flags/w580/ls.png'], 
[ 'LB', 'Libānas Republika', 'Beirūta', 'https://flagpedia.net/data/flags/w580/lb.png'], 
[ 'LR', 'Libērijas Republika', 'Monrovija', 'https://flagpedia.net/data/flags/w580/lr.png'], 
[ 'LY', 'Lībijas Valsts', 'Tripole', 'https://flagpedia.net/data/flags/w580/ly.png'], 
[ 'GB', 'Lielbritānijas un Ziemeļīrijas Apvienotā Karaliste', 'Londona', 'https://flagpedia.net/data/flags/w580/gb.png'], 
[ 'LT', 'Lietuvas Republika', 'Viļņa', 'https://flagpedia.net/data/flags/w580/lt.png'], 
[ 'LI', 'Lihtenšteinas Firstiste', 'Vaduca', 'https://flagpedia.net/data/flags/w580/li.png'], 
[ 'LU', 'Luksemburgas Lielhercogiste', 'Luksemburga', 'https://flagpedia.net/data/flags/w580/lu.png'], 
[ 'MG', 'Madagaskaras Republika', 'Antananarivu', 'https://flagpedia.net/data/flags/w580/mg.png'], 
[ 'YT', 'Francijas Majotas departaments', 'Dzaudzi', 'https://flagpedia.net/data/flags/w580/yt.png'], 
[ 'MO', 'Makao īpašais administratīvais reģions (ĶTR)', 'Aomiņa', 'https://flagpedia.net/data/flags/w580/mo.png'], 
[ 'MY', 'Malaizija', 'Kualalumpura', 'https://flagpedia.net/data/flags/w580/my.png'], 
[ 'MW', 'Malāvijas Republika', 'Lilongve', 'https://flagpedia.net/data/flags/w580/mw.png'], 
[ 'MV', 'Maldīvijas Republika', 'Male', 'https://flagpedia.net/data/flags/w580/mv.png'], 
[ 'ML', 'Mali Republika', 'Bamako', 'https://flagpedia.net/data/flags/w580/ml.png'], 
[ 'MT', 'Maltas Republika', 'Valleta', 'https://flagpedia.net/data/flags/w580/mt.png'], 
[ 'MA', 'Marokas Karaliste', 'Rabāta', 'https://flagpedia.net/data/flags/w580/ma.png'], 
[ 'MH', 'Māršala Salu Republika', 'Madžuro', 'https://flagpedia.net/data/flags/w580/mh.png'], 
[ 'MQ', 'Francijas Martinikas departaments', 'Fordefransa (admin. centrs)', 'https://flagpedia.net/data/flags/w580/mq.png'], 
[ 'MU', 'Maurīcijas Republika', 'Portluī', 'https://flagpedia.net/data/flags/w580/mu.png'], 
[ 'MR', 'Mauritānijas Islāma Republika', 'Nuakšota', 'https://flagpedia.net/data/flags/w580/mr.png'], 
[ 'MX', 'Meksikas Savienotās Valstis', 'Mehiko', 'https://flagpedia.net/data/flags/w580/mx.png'], 
[ 'ME', 'Melnkalne', 'Podgorica', 'https://flagpedia.net/data/flags/w580/me.png'], 
[ 'IM', 'Menas sala', 'Daglasa (admin. centrs)', 'https://flagpedia.net/data/flags/w580/im.png'], 
[ 'FM', 'Mikronēzijas Federatīvās Valstis', 'Palikira', 'https://flagpedia.net/data/flags/w580/fm.png'], 
[ 'MM', 'Mjanmas Savienības Republika', 'Nepjido', 'https://flagpedia.net/data/flags/w580/mm.png'], 
[ 'MD', 'Moldovas Republika', 'Kišiņeva', 'https://flagpedia.net/data/flags/w580/md.png'], 
[ 'MC', 'Monako Firstiste', 'Monako', 'https://flagpedia.net/data/flags/w580/mc.png'], 
[ 'MN', 'Mongolija', 'Ulanbatora', 'https://flagpedia.net/data/flags/w580/mn.png'], 
[ 'MS', 'Montserratas teritorija', 'Plimuta', 'https://flagpedia.net/data/flags/w580/ms.png'], 
[ 'MZ', 'Mozambikas Republika', 'Maputu', 'https://flagpedia.net/data/flags/w580/mz.png'], 
[ 'NA', 'Namībijas Republika', 'Vindhuka', 'https://flagpedia.net/data/flags/w580/na.png'], 
[ 'NR', 'Nauru Republika', 'oficiālas galvaspilsētas nav;', 'https://flagpedia.net/data/flags/w580/nr.png'], 
[ 'NP', 'Nepālas Demokrātiskā Federatīvā Republika', 'Katmandu', 'https://flagpedia.net/data/flags/w580/np.png'], 
[ 'NL', 'Nīderlande', 'Amsterdama / Hāga', 'https://flagpedia.net/data/flags/w580/nl.png'], 
[ 'NE', 'Nigēras Republika', 'Niameja', 'https://flagpedia.net/data/flags/w580/ne.png'], 
[ 'NG', 'Nigērijas Federatīvā Republika', 'Abudža', 'https://flagpedia.net/data/flags/w580/ng.png'], 
[ 'NI', 'Nikaragvas Republika', 'Managva', 'https://flagpedia.net/data/flags/w580/ni.png'], 
[ 'NU', 'Niue', 'Alofi', 'https://flagpedia.net/data/flags/w580/nu.png'], 
[ 'NF', 'Norfolkas salas teritorija', 'Kingstona', 'https://flagpedia.net/data/flags/w580/nf.png'], 
[ 'NO', 'Norvēģijas Karaliste', 'Oslo', 'https://flagpedia.net/data/flags/w580/no.png'], 
[ 'AX', 'Olandes salas', 'Mariehamna', 'https://flagpedia.net/data/flags/w580/ax.png'], 
[ 'OM', 'Omānas Sultanāts', 'Maskata', 'https://flagpedia.net/data/flags/w580/om.png'], 
[ 'PK', 'Pakistānas Islāma Republika', 'Islāmābāda', 'https://flagpedia.net/data/flags/w580/pk.png'], 
[ 'PW', 'Palau Republika', 'Melegeoka', 'https://flagpedia.net/data/flags/w580/pw.png'], 
[ 'PS', 'Palestīnas Valsts', 'Jeruzaleme – proklamēta;', 'https://flagpedia.net/data/flags/w580/ps.png'], 
[ 'PA', 'Panamas Republika', 'Panama', 'https://flagpedia.net/data/flags/w580/pa.png'], 
[ 'PG', 'Papua–Jaungvinejas* Neatkarīgā Valsts', 'Portmorsbija', 'https://flagpedia.net/data/flags/w580/pg.png'], 
[ 'PY', 'Paragvajas Republika', 'Asunsjona', 'https://flagpedia.net/data/flags/w580/py.png'], 
[ 'PE', 'Peru Republika', 'Lima', 'https://flagpedia.net/data/flags/w580/pe.png'], 
[ 'PN', 'Pitkērnas salu teritorija', 'Adamstauna', 'https://flagpedia.net/data/flags/w580/pn.png'], 
[ 'PL', 'Polijas Republika', 'Varšava', 'https://flagpedia.net/data/flags/w580/pl.png'], 
[ 'PT', 'Portugāles Republika', 'Lisabona', 'https://flagpedia.net/data/flags/w580/pt.png'], 
[ 'PR', 'Puertoriko Sadraudzība', 'Sanhuana', 'https://flagpedia.net/data/flags/w580/pr.png'], 
[ 'RE', 'Francijas Reinjonas departaments', 'Sendenī (admin. centrs)', 'https://flagpedia.net/data/flags/w580/re.png'], 
[ 'EH', 'Sahāras Arābu Demokrātiskā Republika', 'Ajūna', 'https://flagpedia.net/data/flags/w580/eh.png'], 
[ 'RW', 'Ruandas Republika', 'Kigali', 'https://flagpedia.net/data/flags/w580/rw.png'], 
[ 'RO', 'Rumānija', 'Bukareste', 'https://flagpedia.net/data/flags/w580/ro.png'], 
[ 'SV', 'Salvadoras Republika', 'Sansalvadora', 'https://flagpedia.net/data/flags/w580/sv.png'], 
[ 'WS', 'Samoa Neatkarīgā Valsts', 'Apija', 'https://flagpedia.net/data/flags/w580/ws.png'], 
[ 'SM', 'Sanmarīno Republika', 'Sanmarīno', 'https://flagpedia.net/data/flags/w580/sm.png'], 
[ 'ST', 'Santomē un Prinsipi Demokrātiskā Republika', 'Santomē', 'https://flagpedia.net/data/flags/w580/st.png'], 
[ 'SA', 'Saūda Arābijas Karaliste', 'Rijāda', 'https://flagpedia.net/data/flags/w580/sa.png'], 
[ 'SC', 'Seišelu Salu Republika', 'Viktorija', 'https://flagpedia.net/data/flags/w580/sc.png'], 
[ 'BL', 'Francijas Senbartelmī teritorija', 'Gustavija', 'https://flagpedia.net/data/flags/w580/bl.png'], 
[ 'SN', 'Senegālas Republika', 'Dakāra', 'https://flagpedia.net/data/flags/w580/sn.png'], 
[ 'MF', 'Francijas Senmartēnas teritorija', 'Marigo', 'https://flagpedia.net/data/flags/w580/mf.png'], 
[ 'PM', 'Francijas Senpjēras un Mikelonas kopiena', 'Senpjēra', 'https://flagpedia.net/data/flags/w580/pm.png'], 
[ 'KN', 'Sentkitsas un Nevisas Federācija', 'Bastera', 'https://flagpedia.net/data/flags/w580/kn.png'], 
[ 'LC', 'Sentlūsija', 'Kastri', 'https://flagpedia.net/data/flags/w580/lc.png'], 
[ 'VC', 'Sentvinsenta un Grenadīnas', 'Kingstauna', 'https://flagpedia.net/data/flags/w580/vc.png'], 
[ 'RS', 'Serbijas Republika', 'Belgrada', 'https://flagpedia.net/data/flags/w580/rs.png'], 
[ 'SG', 'Singapūras Republika', 'Singapūra', 'https://flagpedia.net/data/flags/w580/sg.png'], 
[ 'SX', 'Sintmārtena', 'Filipsburga', 'https://flagpedia.net/data/flags/w580/sx.png'], 
[ 'SY', 'Sīrijas Arābu Republika', 'Damaska', 'https://flagpedia.net/data/flags/w580/sy.png'], 
[ 'SL', 'Sjerraleones Republika', 'Frītauna', 'https://flagpedia.net/data/flags/w580/sl.png'], 
[ 'SK', 'Slovākijas Republika', 'Bratislava', 'https://flagpedia.net/data/flags/w580/sk.png'], 
[ 'SI', 'Slovēnijas Republika', 'Ļubļana', 'https://flagpedia.net/data/flags/w580/si.png'], 
[ 'SO', 'Somālijas Federatīvā Republika', 'Mogadīšo', 'https://flagpedia.net/data/flags/w580/so.png'], 
[ 'FI', 'Somijas Republika', 'Helsinki', 'https://flagpedia.net/data/flags/w580/fi.png'], 
[ 'ES', 'Spānijas Karaliste', 'Madride', 'https://flagpedia.net/data/flags/w580/es.png'], 
[ 'SD', 'Sudānas Republika', 'Hartūma', 'https://flagpedia.net/data/flags/w580/sd.png'], 
[ 'SR', 'Surinamas Republika', 'Paramaribo', 'https://flagpedia.net/data/flags/w580/sr.png'], 
[ 'SJ', 'Svalbāras arhipelāga un Jana Majena salas teritorija', 'Longjērbīene (admin. centrs)', 'https://flagpedia.net/data/flags/w580/sj.png'], 
[ 'SZ', 'Svatini Karaliste', 'Mbabane', 'https://flagpedia.net/data/flags/w580/sz.png'], 
[ 'SH', 'Svētās Helēnas salas, Debesbraukšanas salas un Tristana da Kuņas salu teritorija', 'Džeimstauna', 'https://flagpedia.net/data/flags/w580/sh.png'], 
[ 'LK', 'Šrilankas Demokrātiskā Sociālistiskā Republika', 'Šrī Džajavardenepura Kote', 'https://flagpedia.net/data/flags/w580/lk.png'], 
[ 'CH', 'Šveices Konfederācija', 'Berne', 'https://flagpedia.net/data/flags/w580/ch.png'], 
[ 'TJ', 'Tadžikistānas Republika', 'Dušanbe', 'https://flagpedia.net/data/flags/w580/tj.png'], 
[ 'TW', 'Ķīnas Republika Taivānā', 'Taibeja', 'https://flagpedia.net/data/flags/w580/tw.png'], 
[ 'TH', 'Taizemes Karaliste', 'Bangkoka', 'https://flagpedia.net/data/flags/w580/th.png'], 
[ 'TZ', 'Tanzānijas Savienotā Republika', 'Dodoma', 'https://flagpedia.net/data/flags/w580/tz.png'], 
[ 'TC', 'Tērksas un Kaikosas salu teritorija', 'Kokbērntauna', 'https://flagpedia.net/data/flags/w580/tc.png'], 
[ 'TG', 'Togo Republika', 'Lome', 'https://flagpedia.net/data/flags/w580/tg.png'], 
[ 'TK', 'Tokelau', 'Fakaofo', 'https://flagpedia.net/data/flags/w580/tk.png'], 
[ 'TO', 'Tongas Karaliste', 'Nukualofa', 'https://flagpedia.net/data/flags/w580/to.png'], 
[ 'TT', 'Trinidādas un Tobāgo Republika', 'Portofspeina', 'https://flagpedia.net/data/flags/w580/tt.png'], 
[ 'TN', 'Tunisijas Republika', 'Tunisa', 'https://flagpedia.net/data/flags/w580/tn.png'], 
[ 'TR', 'Turcijas Republika', 'Ankara', 'https://flagpedia.net/data/flags/w580/tr.png'], 
[ 'TM', 'Turkmenistāna', 'Ašgabata', 'https://flagpedia.net/data/flags/w580/tm.png'], 
[ 'TV', 'Tuvalu', 'Funafuti', 'https://flagpedia.net/data/flags/w580/tv.png'], 
[ 'UG', 'Ugandas Republika', 'Kampala', 'https://flagpedia.net/data/flags/w580/ug.png'], 
[ 'UA', 'Ukraina', 'Kijeva', 'https://flagpedia.net/data/flags/w580/ua.png'], 
[ 'HU', 'Ungārija', 'Budapešta', 'https://flagpedia.net/data/flags/w580/hu.png'], 
[ 'UY', 'Urugvajas Austrumu Republika', 'Montevideo', 'https://flagpedia.net/data/flags/w580/uy.png'], 
[ 'UZ', 'Uzbekistānas Republika', 'Taškenta', 'https://flagpedia.net/data/flags/w580/uz.png'], 
[ 'DE', 'Vācijas Federatīvā Republika (VFR)', 'Berlīne', 'https://flagpedia.net/data/flags/w580/de.png'], 
[ 'VU', 'Vanuatu', 'Vila', 'https://flagpedia.net/data/flags/w580/vu.png'], 
[ 'VA', 'Vatikāna Pilsētvalsts (Svētais Krēsls)', 'Vatikāns', 'https://flagpedia.net/data/flags/w580/va.png'], 
[ 'VE', 'Venecuēlas Bolivāra Republika', 'Karakasa', 'https://flagpedia.net/data/flags/w580/ve.png'], 
[ 'VN', 'Vjetnamas Sociālistiskā Republika', 'Hanoja', 'https://flagpedia.net/data/flags/w580/vn.png'], 
[ 'WF', 'Volisa un Futunas salu teritorija', 'Matāutu', 'https://flagpedia.net/data/flags/w580/wf.png'], 
[ 'SB', 'Zālamana Salas', 'Honiara', 'https://flagpedia.net/data/flags/w580/sb.png'], 
[ 'ZM', 'Zambijas Republika', 'Lusaka', 'https://flagpedia.net/data/flags/w580/zm.png'], 
[ 'KP', 'Korejas Tautas Demokrātiskā Republika (KTDR)', 'Phenjana', 'https://flagpedia.net/data/flags/w580/kp.png'], 
[ 'MK', 'Ziemeļmaķedonijas Republika', 'Skopje', 'https://flagpedia.net/data/flags/w580/mk.png'], 
[ 'MP', 'Ziemeļu Marianas Salu Sadraudzība', 'Garapana', 'https://flagpedia.net/data/flags/w580/mp.png'], 
[ 'CX', 'Ziemsvētku salas teritorija', 'Flaingfiškouva', 'https://flagpedia.net/data/flags/w580/cx.png'], 
[ 'ZW', 'Zimbabves Republika', 'Harare', 'https://flagpedia.net/data/flags/w580/zw.png'], 
[ 'SE', 'Zviedrijas Karaliste', 'Stokholma', 'https://flagpedia.net/data/flags/w580/se.png'], 
    ];